root: true
parser: babel-eslint
extends: [airbnb, plugin:flowtype/recommended]
plugins: [babel, flowtype]
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
rules:
  import/no-extraneous-dependencies: [error, {}]
  no-lone-blocks: off
  react/jsx-filename-extension: off
  no-mixed-operators: off # incompatible with prettier
